/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xyz.dsemikin.das.dirdiff.app;

import xyz.dsemikin.das.dirdiff.list.LinkedList;

import static xyz.dsemikin.das.dirdiff.utilities.StringUtils.join;
import static xyz.dsemikin.das.dirdiff.utilities.StringUtils.split;
import static xyz.dsemikin.das.dirdiff.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
